version: '3'
services:
  web:
    build:
      context: ./docker/construct_web      # Dockerfile保存場所
      dockerfile: Dockerfile-web    # Dockerfileファイル名
    image: nn-web-2                 # docker image name
    ports:
      - 80:80
    depends_on: 
      - app      

  app:
    build:
      context: ./docker/construct_app      # Dockerfile保存場所
      dockerfile: Dockerfile-app    # Dockerfileファイル名
    image: nn-app-2                 # docker image name
    ports:                          # ポート接続
      - 3000:3000
    volumes:                        # mount workdir
      - ./myapp:/src
#    command: [sh, -c, npm install && npm start]
    command: [sh, -c, npm run build && npm run start]


